imrunicorn/api/urls.py
from django.urls import path, include
from . import views
from content_collection import views as c_views
# from meme_leach import views as meme_leach_views
from rest_framework import routers
from django.views.generic import TemplateView
# from api.views import ChartData as GroundHogChartData
from groundhog_logbook.views import ChartDataBySex
# from api.views import ChartDataTest
from .views import ActivityLogViewSet

# similar to object based url building
router = routers.DefaultRouter()
router.get_api_root_view().cls.__name__ = "Data Simplified"
router.get_api_root_view().cls.__doc__ = "Data is the backbone to a digital wonderland."

router.register('accounts', views.Accounts)

router.register('activity_log/activity', views.ActivityViewSet)
router.register('activity_log/activity_log', views.ActivityLogViewSet)
router.register('activity_log/activity_photo_validation', views.ActivityPhotoValidationViewSet)

router.register('announcements/what_is_new', views.WhatIsNewView)
router.register('announcements/main_page_blurbs', views.MainPageBlurbsView)
router.register('announcements/page_blurb_overrides', views.PageBlurbOverridesView)

router.register('content_collection/insults', views.ContentCollectionInsultsViewSet)
router.register('content_collection/SensorReading', views.SensorReadingViewSet, basename='SensorReading')

router.register('content_collection/LastSensorReading', views.LastSensorReadingViewSet)

router.register('deer_harvest_logbook/Harvests', views.HarvestsView)
router.register('deer_harvest_logbook/HarvestsPhotos', views.HarvestsPhotosView)

router.register('deer_wait_list/Recipient', views.DeerWaitListRecipient)
router.register('deer_wait_list/MeatCut', views.DeerWaitListMeatCut)
router.register('deer_wait_list/Flavor', views.DeerWaitListFlavor)
router.register('deer_wait_list/RequestedOrder', views.DeerWaitListRequestedOrder)

router.register('docker_hub_webhook', views.DockerWebhookView)

router.register('groundhog_logbook/Location', views.LocationView)
router.register('groundhog_logbook/RemovalsByLocation', views.RemovalsByLocationView)

# router.register('loaddata/Owner', views.Owner)        # this causes a bug with /api/accounts
router.register('loaddata/Caliber', views.LoadDataCaliber)
router.register('loaddata/Firearm', views.LoadDataFirearm)
router.register('loaddata/Powder', views.LoadDataPowder)
router.register('loaddata/Projectile', views.LoadDataProjectile)
router.register('loaddata/Brass', views.LoadDataBrass)
router.register('loaddata/Primer', views.LoadDataPrimer)
router.register('loaddata/HandLoad', views.LoadDataHandLoad)
router.register('loaddata/EstimatedDope', views.LoadDataEstimatedDope)

router.register('meme_leach', views.MemeLeachViewSet)
router.register('motion_readings', views.MotionReadingsViewSet)

router.register('shooting_challenge/ChallengeEvent', views.ChallengeEventViewSet)
router.register('shooting_challenge/ChallengePhoto', views.ChallengePhotoViewSet)


# HyperlinkedModelSerializer doesn't like namespace addressing for the 'url' to work
# app_name = 'api'
urlpatterns = [
    # path('DeerWaitListRecipient/', views.DeerWaitListRecipient, name='DeerWaitListRecipient'),
    # path("activity_log", ActivityLogViewSet.as_view(), name='activity_log'),
    path('', include(router.urls)),
    # this is used for docker hub to push via webhook. It's not classy, but it works.
    path('docker_hub_hook/', views.docker_hub_webhook_unclassy, name='docker_hub_webhook_unclassy'),
    path('sensor_reading/', c_views.sensor_readings, name='sensor_readings'),
    path('meme_leach/<str:subreddit>', views.random_meme_by_subreddit),
]

imrunicorn/content_collection/urls.py
from django.urls import path, include
from . import views

app_name = 'content_collection'
urlpatterns = [
    path('', views.page_home, name='home'),

    path('todo/', views.page_todo, name='todo'),

    path('canvasjs/', views.page_canvasjs, name='canvasjs'),

    path('general/', views.page_general_uploads, name='general_uploads'),

    path('sensor_readings/', views.page_sensor_readings, name='sensor_readings'),
    path('sensor_readings/<str:sensor_shortname>', views.page_sensor_readings_by_sensor_shortname, name='sensor_readings'),
    #me='sensor_readings'),
    #path('loads/<str:load_type>', views.page_loads_by_type, name='loads'),


    path('videos/', views.page_video_list, name='video_list'),
    path('videos/<int:video_pk>', views.page_latest_video_by_pk, name='video_list'),

    path('videos/latest', views.page_latest_video, name='videos_latest'),

    path('carousel', views.page_carousel, name='carousel'),
    path('carousel/recent', views.page_carousel_recent, name='carousel_recent'),

    path('dnd5e', views.page_dnd5e_list, name='dnd5e_list'),
    path('fantasy_grounds', views.page_fantasy_grounds_list, name='fantasy_grounds_list'),

    path('insult', views.leach_insult, name='insult'),
    path('insult_list_all', views.insult_list_all, name='insult_list_all'),

    path('secrets_list_all', views.secrets_list_all, name='secrets_list_all'),

    path('buzz_words_or_phrases_list_all', views.buzz_words_or_phrases_list_all, name='buzz_words_or_phrases_list_all'),

    # path('dnd5e/<int:dnd5e_pk>', views.page_dnd5e_list_by_pk, name='dnd5e_list'),

    path('sketches/', views.page_sketch_list, name='sketches'),
    path('sketches/<int:sketch_pk>', views.page_sketch_by_pk, name='sketches'),

]

imrunicorn/imrunicorn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from django.conf import settings
# from . import forms, views
from announcements.get_news import get_news, get_version_json
from django.conf import settings
from django.conf.urls.static import static
from . import forms, views


# app_name = 'base_skipped_for_now'
urlpatterns = [
    path('api/', include('api.urls')),
    path('test/', views.page_test_layout, name='test_layout'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/weather/', views.page_api_weather, name='page_api_weather'),
    path('qr/about/', views.page_qr_about, name='qr_about'),
    path('admin/', admin.site.urls),
    path('', views.page_home, name='home'),

    path('access_denied_groups', views.page_access_denied_groups, name='access_denied_groups'),

    path('page_hits/', views.page_page_hits, name='page_hits'),

    path('foia/', views.page_foia, name='page_foia'),

    path('activity_log/', include('activity_log.urls')),
    path('announcements/', include('announcements.urls')),
    path('load_data/', include('loaddata.urls')),
    path('farm_invite/', include('farminvite.urls')),
    path('polls/', include('polls.urls')),
    path('shooting_logbook/', include('shooting_logbook.urls')),
    path('groundhog_logbook/', include('groundhog_logbook.urls')),
    path('deer_harvest_logbook/', include('deer_harvest_logbook.urls')),
    path('deer_wait_list/', include('deer_wait_list.urls')),
    path('admin_toolbox/', include('admin_toolbox.urls')),
    path('status_watcher/', include('status_watcher.urls')),
    path('content_collection/', include('content_collection.urls')),
    path('call_of_the_wild/', include('call_of_the_wild.urls')),
    path('shooting_challenge/', include('shooting_challenge.urls')),
    path('dcsa_info/', include('dcsa_info.urls')),
    path('bingo/', include('bingo.urls')),
    # path('puppy_fostering/', include('puppy_fostering.urls')),
    path('meme_leach/', include('meme_leach.urls')),
    path('dad_jokes/', include('dad_jokes.urls')),
    path('event_photo_album/', include('event_photo_album.urls')),


    # path('contact/', views.contact, name='contact'),
    # path('about/', views.about, name='about'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('login/',
         LoginView.as_view
             (
             template_name='imrunicorn/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log In',
                 'copy_year': datetime.now().year,
                 'release': get_version_json(),
                 'blurb': 'I am not allowing new accounts at this time.',
                 'no_accounts_blurb': 'If you have an account and need a reset, you know how to reach me..',
             }
         ),
         name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # https://docs.djangoproject.com/en/2.0/topics/http/views/#customizing-error-views
# handler404 = 'YOUR_APP_NAME.views.handler404'

handler404 = 'imrunicorn.views.handler404'
handler403 = 'imrunicorn.views.handler403'
handler500 = 'imrunicorn.views.handler500'

imrunicorn/content_collection/models.py
from datetime import datetime, date, timedelta
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.utils.timezone import now


def in_three_days():
    django_now = now
    return django_now + timedelta(days=3)


class GeneralUpload(models.Model):
    file_title = models.CharField(max_length=150, default=None, blank=True, null=True)
    path = models.FileField(upload_to='uploads/general/', null=True, blank=True)
    # keep_alive_until = models.DateTimeField(default=in_three_days())
    keep_alive_until = models.DateTimeField()

    def __str__(self):
        return "%s - %s" % (self.keep_alive_until, self.file_title)

    class Meta:
        ordering = ('keep_alive_until', '-pk')


class Video(models.Model):
    file_title = models.CharField(max_length=150, default=None, blank=True, null=True)
    file_name = models.FileField(upload_to='uploads/content_collection/videos/', null=True, blank=True)
    restricted = models.BooleanField(default=True, null=True)

    def __str__(self):
        return "#%s - [%s] %s (%s)" % (self.pk, self.restricted, self.file_title, self.file_name)

    class Meta:
        ordering = ('-pk', 'restricted', 'file_title', 'file_name')


class PicturesForCarousel(models.Model):
    caption = models.CharField(max_length=250, null="no name yet", blank="no name yet", default="no name yet")
    picture = models.ImageField(upload_to='uploads/carousel/', null=True, blank=True)
    link_to_external = models.CharField(max_length=250, null=True, blank=True)
    restricted = models.BooleanField(default=True, null=True)

    def __str__(self):
        return self.caption

    class Meta:
        ordering = ('-pk', 'caption')
        verbose_name = 'Picture For Carousel'
        verbose_name_plural = 'Pictures For Carousel'


class DAndDFifthEditionBook(models.Model):
    file_title = models.CharField(max_length=150, default=None, blank=True, null=True)
    file_name = models.FileField(upload_to='uploads/content_collection/dnd5e_books/', null=True, blank=True)
    restricted = models.BooleanField(default=True, null=True)

    def __str__(self):
        return "#%s [%s]- %s (%s)" % (self.pk, self.restricted, self.file_title, self.file_name)

    class Meta:
        ordering = ('-pk', 'file_title', 'file_name')
        verbose_name = 'D & D 5th Edition Book'
        verbose_name_plural = 'D & D 5th Edition Book'


class FantasyGrounds(models.Model):
    file_title = models.CharField(max_length=150, default=None, blank=True, null=True)
    file_name = models.FileField(upload_to='uploads/content_collection/FantasyGrounds/', null=True, blank=True)

    def __str__(self):
        return "#%s - %s (%s)" % (self.pk, self.file_title, self.file_name)

    class Meta:
        ordering = ('-pk', 'file_title', 'file_name')
        verbose_name = 'Fantasy Grounds'
        verbose_name_plural = 'Fantasy Grounds'


class RandomInsult(models.Model):
    insult = models.TextField(unique=True, blank=True, null=True)  # i like big comments...

    def __str__(self):
        return "[%s] %s" % (self.pk, self.insult)

    class Meta:
        ordering = ('-pk', 'insult')
        verbose_name = 'Random Insult'
        verbose_name_plural = 'Random Insults'


class Secret(models.Model):
    title = models.CharField(max_length=150)
    message = models.TextField(blank=True, null=True)  # i like big comments...

    def __str__(self):
        return "[%s] %s" % (self.pk, self.title)

    class Meta:
        ordering = ('-pk', )
        verbose_name = 'Secret'
        verbose_name_plural = 'Secrets'


class BuzzWordOrPhrase(models.Model):
    word_or_phrase = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return "[%s] %s" % (self.pk, self.word_or_phrase)

    class Meta:
        ordering = ('-pk', )
        verbose_name = 'Buzzword or Phrase'
        verbose_name_plural = 'Buzzwords or Phrases'


class SensorReadings(models.Model):
    read_datetime = models.DateTimeField(auto_now_add=True, blank=True)
    sensor_location = models.CharField(max_length=150)
    sensor_model = models.CharField(max_length=150, default="DHT22")
    celsius = models.DecimalField(max_digits=5, decimal_places=2, default=1.21)
    fahrenheit = models.DecimalField(max_digits=5, decimal_places=2, default=5.56)
    humidity = models.DecimalField(max_digits=4, decimal_places=2, default=7.62)

    def __str__(self):
        return "%s - %s" % (self.read_datetime, self.sensor_location)

    class Meta:
        ordering = ('-read_datetime', )
        verbose_name = 'Sensor Reading'
        verbose_name_plural = 'Sensor Readings'


class ArduinoUnoSketch(models.Model):
    sketch_datetime = models.DateTimeField(auto_now_add=True, blank=True)
    title = models.CharField(max_length=150)
    intent = models.TextField(blank=True, null=True)  # i like big comments...
    sketch = models.TextField(blank=True, null=True)  # i like big comments...
    restricted = models.BooleanField(default=False, null=True)

    def __str__(self):
        return "%s - %s" % (self.sketch_datetime, self.title)

    class Meta:
        ordering = ('-sketch_datetime', )
        verbose_name = 'Arduino Uno Sketch'
        verbose_name_plural = 'Arduino Uno Sketches'


class MotionReadings(models.Model):
    read_datetime = models.DateTimeField(auto_now_add=True, blank=True)
    sensor_location = models.CharField(max_length=150)
    sensor_model = models.CharField(max_length=150, default="DHT22")
    message = models.TextField(blank=True, null=True)  # i like big comments...

    def __str__(self):
        return "%s - %s" % (self.read_datetime, self.sensor_location)

    class Meta:
        ordering = ('-read_datetime', '-id')
        verbose_name = 'Motion Reading'
        verbose_name_plural = 'Motion Readings'

imrunicorn/content_collection/forms.py
from django import forms
from .models import GeneralUpload


class GeneralUploadForm(forms.ModelForm):
    class Meta:
        model = GeneralUpload
        fields = ('path', 'file_title', 'keep_alive_until')

imrunicorn/content_collection/templates/content_collection/blank.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>

<div class="row ben_format_pretty">
    This page is blank, mostly.
</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/buzz_words_or_phrases_list_all.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            This might take a bit to load, thank you for your patience.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />


<div class="row ben_format_pretty">
    Not to worry, there are more buzz words coming for management reasons.

    {% if new_words_or_phrases > 0 %}
        We were able to find {{ new_words_or_phrases }} more
            {% if new_words_or_phrases > 1 %}
                buzzwords
            {% else %}
                buzzword
            {% endif %}
        just now, so the list has been updated to reflect that.
    {% endif %}
    <br /><br /><br />

    {% for word in words %}

        <strong>{{ word.pk }}:</strong> {{ word.word_or_phrase }}<br />

        {% if forloop.last  == True %}
            <br />
        {% endif %}

    {% endfor %}
</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/canvasjs.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	theme: "light2",
	title:{
		text: "Simple Line Chart"
	},
	data: [{
		type: "line",
      	indexLabelFontSize: 16,
		dataPoints: [
			{ y: 450 },
			{ y: 414},
			{ y: 520, indexLabel: "\u2191 highest",markerColor: "red", markerType: "triangle" },
			{ y: 460 },
			{ y: 450 },
			{ y: 500 },
			{ y: 480 },
			{ y: 480 },
			{ y: 410 , indexLabel: "\u2193 lowest",markerColor: "DarkSlateGrey", markerType: "cross" },
			{ y: 500 },
			{ y: 480 },
			{ y: 510 }
		]
	}]
});
chart.render();

}
</script>
{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>

<div class="row ben_format_pretty">
    <div id="chartContainer" style="height: 370px; width: 100%;"></div>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/carousel-sample-lkg.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>

<div class="row ben_format_pretty">
    Carousel pictures, are not restricted here.<br /><br />

    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">

                {% for item in carousel %}
                    {% if forloop.first %}
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    {% else %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter}}"></li>
                    {% endif %}
                {% endfor %}
            </ol>
            <div class="carousel-inner">

                {% for item in carousel %}
                    {% if forloop.first %}
                        <div class="item active">
                            {% if item.picture.url != None %}
                                <img class="slide-image" src="{{ item.picture.url }}" alt="{{ item.caption }}">
                            {% else %}
                                {% if item.link_to_external|first in 'http' %}
                                    <img class="slide-image" src="{{ item.link_to_external }}" alt="{{ item.caption }}">
                                {% else %}
                                    <img class="slide-image" src="{{request.scheme}}://{{request.get_host}}{{ item.link_to_external }}" alt="{{ item.caption }}">
                                {% endif %}
                            {% endif %}
                        </div>
                    {% else %}
                        <div class="item">
                            {% if item.picture.url != None %}
                                <img class="slide-image" src="{{ item.picture.url }}" alt="{{ item.caption }}">
                            {% else %}
                                {% if item.link_to_external|first in 'http' %}
                                    <img class="slide-image" src="{{ item.link_to_external }}" alt="{{ item.caption }}">
                                {% else %}
                                    <img class="slide-image" src="{{request.scheme}}://{{request.get_host}}{{ item.link_to_external }}" alt="{{ item.caption }}">
                                {% endif %}
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}


            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>

        </div>
    </div>






</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/carousel.html
{% extends "imrunicorn/layout.html" %}
{% load static %}


{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />

<div class="row ben_format_pretty">

    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">

                {% for item in carousel %}
                    {% if forloop.first %}
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    {% else %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter}}"></li>
                    {% endif %}
                {% endfor %}
            </ol>
            <div class="carousel-inner">

                {% for item in carousel %}
                    {% if forloop.first %}
                        <div class="item active">
                            {% if item.restricted %}
                                {% if unrestricted_user %}
                                    {% if item.picture.url != None %}
                                        <img class="slide-image" src="{{ item.picture.url }}" alt="{{ item.caption }}">
                                    {% else %}
                                        <img class="slide-image" src="{{ item.link_to_external }}" alt="{{ item.caption }}">
                                    {% endif %}
                                {% else %}
                                    <img class="slide-image" src="{% static '/content_collection/restricted.png' %}" alt="restricted image">
                                {% endif %}
                            {% else %}
                                    {% if item.picture.url != None %}
                                        <img class="slide-image" src="{{ item.picture.url }}" alt="{{ item.caption }}">
                                    {% else %}
                                        <img class="slide-image" src="{{ item.link_to_external }}" alt="{{ item.caption }}">
                                    {% endif %}
                            {% endif %}
                        </div>
                    {% else %}
                        <div class="item">
                            {% if item.restricted %}
                                {% if unrestricted_user %}
                                    {% if item.picture.url != None %}
                                        <img class="slide-image" src="{{ item.picture.url }}" alt="{{ item.caption }}">
                                    {% else %}
                                        <img class="slide-image" src="{{ item.link_to_external }}" alt="{{ item.caption }}">
                                    {% endif %}
                                {% else %}
                                    <img class="slide-image" src="{% static '/content_collection/restricted.png' %}" alt="restricted image">
                                {% endif %}
                            {% else %}
                                    {% if item.picture.url != None %}
                                        <img class="slide-image" src="{{ item.picture.url }}" alt="{{ item.caption }}">
                                    {% else %}
                                        <img class="slide-image" src="{{ item.link_to_external }}" alt="{{ item.caption }}">
                                    {% endif %}
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}


            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>

        </div>
    </div>






</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/general_uploads.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}


{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            This might take a bit to load, thank you for your patience.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />


<div class="row ben_format_pretty">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
    <br />
     <hr style="height:2px;border-width:0;color:gray;background-color:red" />
    {% for record in secrets %}
        <a href="{{ record.path.url }}" target="_blank">{{ record.file_title }}</a><br />
        EXPIRES: {{ record.keep_alive_until }}
        {% if forloop.last  == False %}
            <hr style="height:2px;border-width:0;color:gray;background-color:red" />
        {% else %}
            <br />
        {% endif %}

    {% endfor %}
</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/highcharts.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>

<div class="row ben_format_pretty">
    <div id="container"></div>
  <script src="https://code.highcharts.com/highcharts.src.js"></script>
  <script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Historic World Population by Region'
        },
        xAxis: {
            categories: ['Africa', 'America', 'Asia', 'Europe', 'Oceania']
        },
        series: [{
            name: 'Year 1800',
            data: [107, 31, 635, 203, 2]
        }, {
            name: 'Year 1900',
            data: [133, 156, 947, 408, 6]
        }, {
            name: 'Year 2012',
            data: [1052, 954, 4250, 740, 38]
        }]
    });
  </script>


</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/insult.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />


<div class="row ben_format_pretty">

    {% for item in insults %}
        <strong>{{ item }}</strong>
        {% if forloop.last  == False %}
            <br /><i>OR</i><br />
        {% else %}
            <br /><br />
            View the <a href="{% url 'content_collection:insult_list_all' %}">insult list</a><br />
            View the <a href="/api/content_collection/insults/" target="_blank">insult list</a> (API LIST)<br />
        {% endif %}
    {% endfor %}


    {% if status_code_message|length > 0 %}
        <br /><br /><i>{{ status_code_message }}</i>
    {% endif %}
</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/video_list.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />


<div class="row ben_format_pretty">
    List of videos, some may be hidden because of access.

    <br /><br />
        <ul>
        {% for item in videos %}
            {% if item.restricted %}
                {% if unrestricted_user %}
                    <li><a href="{% url 'content_collection:video_list' %}{{ item.pk }}">#{{ item.pk }} - {{ item.file_title }}</a>
                {% else %}
                    <li><a href="{% url 'content_collection:video_list' %}{{ item.pk }}">#{{ item.pk }} - [ Title Hidden ]</a>
                {% endif %}
            {% else %}
                <li><a href="{% url 'content_collection:video_list' %}{{ item.pk }}">#{{ item.pk }} - {{ item.file_title}}</a>
            {% endif %}
                </li>
        {% endfor %}
        </ul>

</div>

{% endblock %}