imrunicorn/api/urls.py
from django.urls import path, include
from . import views
from content_collection import views as c_views
# from meme_leach import views as meme_leach_views
from rest_framework import routers
from django.views.generic import TemplateView
# from api.views import ChartData as GroundHogChartData
from groundhog_logbook.views import ChartDataBySex
# from api.views import ChartDataTest
from .views import ActivityLogViewSet

# similar to object based url building
router = routers.DefaultRouter()
router.get_api_root_view().cls.__name__ = "Data Simplified"
router.get_api_root_view().cls.__doc__ = "Data is the backbone to a digital wonderland."

router.register('accounts', views.Accounts)

router.register('activity_log/activity', views.ActivityViewSet)
router.register('activity_log/activity_log', views.ActivityLogViewSet)
router.register('activity_log/activity_photo_validation', views.ActivityPhotoValidationViewSet)

router.register('announcements/what_is_new', views.WhatIsNewView)
router.register('announcements/main_page_blurbs', views.MainPageBlurbsView)
router.register('announcements/page_blurb_overrides', views.PageBlurbOverridesView)

router.register('content_collection/insults', views.ContentCollectionInsultsViewSet)
router.register('content_collection/SensorReading', views.SensorReadingViewSet, basename='SensorReading')

router.register('content_collection/LastSensorReading', views.LastSensorReadingViewSet)

router.register('deer_harvest_logbook/Harvests', views.HarvestsView)
router.register('deer_harvest_logbook/HarvestsPhotos', views.HarvestsPhotosView)

router.register('deer_wait_list/Recipient', views.DeerWaitListRecipient)
router.register('deer_wait_list/MeatCut', views.DeerWaitListMeatCut)
router.register('deer_wait_list/Flavor', views.DeerWaitListFlavor)
router.register('deer_wait_list/RequestedOrder', views.DeerWaitListRequestedOrder)

router.register('docker_hub_webhook', views.DockerWebhookView)

router.register('groundhog_logbook/Location', views.LocationView)
router.register('groundhog_logbook/RemovalsByLocation', views.RemovalsByLocationView)

# router.register('loaddata/Owner', views.Owner)        # this causes a bug with /api/accounts
router.register('loaddata/Caliber', views.LoadDataCaliber)
router.register('loaddata/Firearm', views.LoadDataFirearm)
router.register('loaddata/Powder', views.LoadDataPowder)
router.register('loaddata/Projectile', views.LoadDataProjectile)
router.register('loaddata/Brass', views.LoadDataBrass)
router.register('loaddata/Primer', views.LoadDataPrimer)
router.register('loaddata/HandLoad', views.LoadDataHandLoad)
router.register('loaddata/EstimatedDope', views.LoadDataEstimatedDope)

router.register('meme_leach', views.MemeLeachViewSet)
router.register('motion_readings', views.MotionReadingsViewSet)

router.register('shooting_challenge/ChallengeEvent', views.ChallengeEventViewSet)
router.register('shooting_challenge/ChallengePhoto', views.ChallengePhotoViewSet)


# HyperlinkedModelSerializer doesn't like namespace addressing for the 'url' to work
# app_name = 'api'
urlpatterns = [
    # path('DeerWaitListRecipient/', views.DeerWaitListRecipient, name='DeerWaitListRecipient'),
    # path("activity_log", ActivityLogViewSet.as_view(), name='activity_log'),
    path('', include(router.urls)),
    # this is used for docker hub to push via webhook. It's not classy, but it works.
    path('docker_hub_hook/', views.docker_hub_webhook_unclassy, name='docker_hub_webhook_unclassy'),
    path('sensor_reading/', c_views.sensor_readings, name='sensor_readings'),
    path('meme_leach/<str:subreddit>', views.random_meme_by_subreddit),
]

imrunicorn/farminvite/urls.py
from django.urls import path
from . import views

app_name = 'farm_invite'
urlpatterns = [
    path('', views.page_farm_invites_view, name='home'),
    path('pending/', views.page_farm_invites_view_hidden_listings, name='view_hidden_listings'),
    path('request_slot/', views.page_invite_listing, name='invite_listing'),
    path('missing_contact_info/', views.page_missing_contact_info, name='missing_contact_info'),
    path('checklist/', views.page_farm_check_list, name='check_list'),
    path('map/', views.page_farm_invites_map_fake, name='map_fake'),
    path('how_do_i_sign_up/', views.page_how_to_sign_up, name='how_do_i_sign_up'),
    path('k98k-is-great-m1-garand-wins-wars/', views.page_farm_invites_map, name='map_secret_sort_of'),

    path('packing_list/', views.page_packing_list, name='packing_list'),

    path('cash_app/', views.page_cash_app, name='cash_app'),

]

imrunicorn/imrunicorn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from django.conf import settings
# from . import forms, views
from announcements.get_news import get_news, get_version_json
from django.conf import settings
from django.conf.urls.static import static
from . import forms, views


# app_name = 'base_skipped_for_now'
urlpatterns = [
    path('api/', include('api.urls')),
    path('test/', views.page_test_layout, name='test_layout'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/weather/', views.page_api_weather, name='page_api_weather'),
    path('qr/about/', views.page_qr_about, name='qr_about'),
    path('admin/', admin.site.urls),
    path('', views.page_home, name='home'),

    path('access_denied_groups', views.page_access_denied_groups, name='access_denied_groups'),

    path('page_hits/', views.page_page_hits, name='page_hits'),

    path('foia/', views.page_foia, name='page_foia'),

    path('activity_log/', include('activity_log.urls')),
    path('announcements/', include('announcements.urls')),
    path('load_data/', include('loaddata.urls')),
    path('farm_invite/', include('farminvite.urls')),
    path('polls/', include('polls.urls')),
    path('shooting_logbook/', include('shooting_logbook.urls')),
    path('groundhog_logbook/', include('groundhog_logbook.urls')),
    path('deer_harvest_logbook/', include('deer_harvest_logbook.urls')),
    path('deer_wait_list/', include('deer_wait_list.urls')),
    path('admin_toolbox/', include('admin_toolbox.urls')),
    path('status_watcher/', include('status_watcher.urls')),
    path('content_collection/', include('content_collection.urls')),
    path('call_of_the_wild/', include('call_of_the_wild.urls')),
    path('shooting_challenge/', include('shooting_challenge.urls')),
    path('dcsa_info/', include('dcsa_info.urls')),
    path('bingo/', include('bingo.urls')),
    # path('puppy_fostering/', include('puppy_fostering.urls')),
    path('meme_leach/', include('meme_leach.urls')),
    path('dad_jokes/', include('dad_jokes.urls')),
    path('event_photo_album/', include('event_photo_album.urls')),


    # path('contact/', views.contact, name='contact'),
    # path('about/', views.about, name='about'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('login/',
         LoginView.as_view
             (
             template_name='imrunicorn/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log In',
                 'copy_year': datetime.now().year,
                 'release': get_version_json(),
                 'blurb': 'I am not allowing new accounts at this time.',
                 'no_accounts_blurb': 'If you have an account and need a reset, you know how to reach me..',
             }
         ),
         name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # https://docs.djangoproject.com/en/2.0/topics/http/views/#customizing-error-views
# handler404 = 'YOUR_APP_NAME.views.handler404'

handler404 = 'imrunicorn.views.handler404'
handler403 = 'imrunicorn.views.handler403'
handler500 = 'imrunicorn.views.handler500'

imrunicorn/farminvite/views.py
import json
import os
from datetime import datetime
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.db.models import F, ExpressionWrapper
from django.http import JsonResponse
from django.shortcuts import render
from model_utils.models import now
from .forms import InviteListingForm
from .models import InviteListing
from announcements.get_news import get_news, get_version_json, get_restart_notice, get_page_blurb_override
from .functions import get_packing_list
from imrunicorn.functions import step_hit_count_by_page


def page_packing_list(request):
    list_size = 10
    step_hit_count_by_page(request.path)
    result = get_packing_list(list_size)

    unrestricted = False
    # allowed_groupname_list = ['packing_list_viewer']
    # if request.user.groups.filter(name__in=allowed_groupname_list).exists():
    #     unrestricted = True

    perm_check = request.user.has_perm('farminvite.view_packinglist')
    unrestricted = perm_check

    context = {
        "query_result": result,
        'release': get_version_json(),
        "title": "Packing List",
        'unrestricted_user': unrestricted,
        "blurb": "I started tracking my packing list as of 2021, be patient. I'm only showing a maximum of the "
                 "last {0} times. ".format(list_size),
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/packing_list.html", context)


def unused_json_farm_invites_view(request):
    step_hit_count_by_page(request.path)
    context = {
        'body': 'no body to share',
        'header': 'farm invites view',
    }
    return JsonResponse(context)


def unused_page_farm_invites_view(request):
    step_hit_count_by_page(request.path)
    context = {
        'release': get_version_json(),
        "title": "Coming Soon",
        "blurb": "This page is a place holder for what's to come soon.",
        "table_data": 'Shake it like it\'s going out of style!',
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/coming_soon.html", context)


def page_farm_invites_view(request):
    step_hit_count_by_page(request.path)
    this_moment = datetime.now()
    all_invites = InviteListing.objects.filter(
        Q(Show_Listing=True) &
        Q(Cancel_Code="InviteActive") &
        (Q(Invite_Date=this_moment.date()) |
         Q(Invite_Date__gt=this_moment.date()))).order_by('Invite_Date', 'Invite_Secondary', )

    context = {
        'contact_good': 'Complete',
        'contact_okay': '85%',
        'contact_poor': '66%',
        'contact_bad': 'Incomplete',
        'release': get_version_json(),
        "title": "Farm Range Invites",
        "blurb": "<li>Complete - Registration fee (waved as of 2022) and I have your contact info.</li>"
                 "<li>Incomplete - Something is missing, reach out to me.</li>"
        ,
        'all_invites': all_invites,
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/calendar_list.html", context)


def page_farm_invites_view_lkg(request):
    step_hit_count_by_page(request.path)
    this_moment = datetime.now()
    all_invites = InviteListing.objects.filter(
        Q(Show_Listing=True) &
        Q(Cancel_Code="InviteActive") &
        (Q(Invite_Date=this_moment.date()) |
         Q(Invite_Date__gt=this_moment.date()))).order_by('Invite_Date', 'Invite_Secondary', )

    context = {
        'contact_good': 'COMPLETE',
        'contact_okay': '85%',
        'contact_poor': '66%',
        'contact_bad': '5%',
        'release': get_version_json(),
        "title": "Farm Range Invites",
        "blurb": "Pay attention to the registration completion grade. If the only way to reach you is via MDShooters_LKG "
                 "forms or work chat you are at risk of having your invite retracted to make room for someone else "
                 "that I can communicate with. "
                 "Your invite registration completion will update as the additional info is entered into the "
                 "system.<br /><br /> "
                 "66% is fine, higher is better/easier."
                 "<li>COMPLETE - I have Phone and email to reach you.</li>"
                 "<li>85% - I have your phone number to reach you.</li>"
                 "<li>66% - I have your email to reach you.</li>"
                 "<li>5% - I only have MDShooters_LKG or work chat to reach you. <i>You're at risk of being removed from "
                 "the invites.</i></li> "
                 ""
        ,
        'all_invites': all_invites,
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/calendar_list.html", context)


def page_farm_invites_view_hidden_listings(request):
    step_hit_count_by_page(request.path)
    this_moment = datetime.now()
    all_invites = InviteListing.objects.filter(
        Q(Show_Listing=False) &
        (Q(Invite_Date=this_moment.date()) |
         Q(Invite_Date__gt=this_moment.date()))).order_by('Invite_Date', 'Invite_Secondary', )

    context = {
        'contact_good': 'Complete',
        'contact_bad': 'Incomplete',
        'release': get_version_json(),
        "title": "Invites Pending",
        'all_invites': all_invites,
        "blurb": get_page_blurb_override('/farm_invite/pending/'),
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/calendar_list.html", context)


@permission_required('farminvite.view_invite_listing', login_url='/login', raise_exception=True)
def page_farm_invites_map(request):
    step_hit_count_by_page(request.path)
    context = {
        'release': get_version_json(),
        "title": "Farm Invite: Map",
        "table_data": 'Shake it like it\'s going out of style!',
        # "blurb": get_page_blurb_override('/farm_invite/pending/'),
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/farm_map.html", context)


def page_farm_invites_map_fake(request):
    step_hit_count_by_page(request.path)
    context = {
        'release': get_version_json(),
        "title": "Coming Soon",
        "blurb": "This page is a place holder for what's to come soon.",
        "table_data": 'Shake it like it\'s going out of style!',
        # "blurb": get_page_blurb_override('/farm_invite/pending/'),
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/fake_map.html", context)


def page_farm_check_list(request):
    step_hit_count_by_page(request.path)
    context = {
        'release': get_version_json(),
        "title": "What should I bring?",
        # "blurb": "Pre-pack your car/truck it helps to prevent forgetting things.",
        "blurb": get_page_blurb_override('/farm_invite/pending/'),
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/what_to_bring.html", context)


def page_request_slot(request):
    step_hit_count_by_page(request.path)
    context = {
        'release': get_version_json(),
        "title": "Request Slot",
        "blurb": "Email Me To Request Slot",
        "table_data": 'The email must contain these items or I\'ll ignore the request. I\'ll add you to the secondary '
                      'listing if primary is full. '
                      '<li>FirstName (so i dont call you dude/woman all day):</li>'
                      '<li>Display Name (MDShoters name or something else. This is what\'s displayed on the listing '
                      'page.):</li> '
                      '<li>Phone Number:</li>'
                      '<li>E-Mail:</li>'
                      '<li>Date Of Invite Requesting:</li>'
                      '<li>AM or PM</li>'                      
                      '<li><i>EMAIL SUBJECT: Aim Small Miss Small</i> (other subjects will be ignored)</li>'
                      '<li>My Address: <a href="mailto:Admin@BenSpelledABC.me">Admin@BenSpelledABC.me</a></li>'
                      ''
        ,
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/simple_use_variables.html", context)


def page_cash_app(request):
    step_hit_count_by_page(request.path)
    context = {
        'release': get_version_json(),
        "title": "Donate: Cash App",
        "blurb": "Cash app is our preferred method of payment.",
        "full_body": "",
        # "blurb": get_page_blurb_override('/farm_invite/pending/'),
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/donate_cash_app.html", context)


def page_how_to_sign_up(request):
    step_hit_count_by_page(request.path)
    context = {
        'release': get_version_json(),
        "title": "How to sign up",
        "blurb": "The process has changed for 2022!",
        "cash_app": "Show_QR_Code",
        # "blurb": get_page_blurb_override('/farm_invite/pending/'),
        "copy_year": datetime.now().year
    }
    return render(request, "farminvite/sign_up_how.html", context)


@permission_required('farminvite.view_invite_listing', login_url='/login', raise_exception=True)
def page_missing_contact_info(request):
    step_hit_count_by_page(request.path)
    this_moment = datetime.now()
    all_invites = InviteListing.objects.filter(
        Q(Invite_Date=this_moment.date()) |
        Q(Invite_Date__gt=this_moment.date())).order_by('Invite_Date', 'Invite_Secondary', )

    context = {
        'release': get_version_json(),
        "title": "Registration Completion Guideline",
        "blurb": "Please provide some contact info if you show up on this list as having it missing. Failure to do so "
                 "will result in your name being removed from the invite list to make room for people that I can get "
                 "in touch with. Entries without at least one or the other will be removed five days before the event "
                 "and the invite will be "
                 "sent to the secondary person for that day.<br /><br />"

imrunicorn/farminvite/templates/farminvite/calendar_list.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}
<style>
td.padded {
  padding-left: 10px;
}
</style>
{% endblock %}

{% block content %}
{% load humanize %}

<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">Who's ready and who's not.</p>
</div>


<div class="row ben_format_pretty">
    <div align="center">
    <div>
        {% include 'farminvite/chart_menu.html' %}
    </div>
</div>
</div>

<br />

<div class="row ben_format_pretty">
    <div class="col-md-12">
        <p>Read the <a href="{% url 'farm_invite:how_do_i_sign_up' %}">'Sign Up Info'</a> for more info.<br /><br /></p>
        <p>
            {% autoescape off %}
            {% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}
            {% endautoescape %}
        </p>

        <table width="100%" border="1" align="center">
            <tr bgcolor="#808080">
                <th bgcolor="808080" style="text-align: center">
                    Invite Slot
                </th>
                </th>
                <th bgcolor="808080" style="text-align: center">
                    Display Name
                </th>
                <th bgcolor="808080" style="text-align: center">
                    Registration Completion
                </th>

            </tr>


            {% if all_invites != None %}
                {% for invite in all_invites %}

                <tr bgcolor="#F5F5F5">
                    <td class="padded">{{ invite.Invite_Date|date:'m/d/Y' }} [ID: {{ invite.id }}]</td>

                    {% if request.user|has_group:"farminvite_editor" %}
                    <td class="padded" data-toggle="tooltip"
                        title="Entry Name: {{invite.Invite_Display_Name}}
Paid: {{ invite.Paid}}
RealName: {{ invite.Real_Name }}
Phone: {{ invite.Phone_Number }}
E-Mail: {{ invite.EMail }}
Invite_ID: {{ invite.id }}">
                        <a href="/admin/farminvite/invitelisting/{{ invite.pk }}/change/" target="_blank">
                            <i class="fas fa-edit"></i></a>
                        <a href="/admin/auth/user/add/?username={{ invite.Invite_Display_Name }}" target="_blank">
                            {{ invite.Invite_Display_Name }}</a>
                    </td>
                    {% else %}
                    <td class="padded" data-toggle="tooltip" title="Info Redacted">{{ invite.Invite_Display_Name }}</td>
                    {% endif %}

                    {% if invite.Invite_Display_Name != 'SLOT AVAILABLE' and invite.Invite_Display_Name != 'Tannerite Fun In The Sun' %}
                        {% if invite.Paid %}
                            <td class="padded">{{ contact_good }}</td>
                        {% else %}
                            <td class="padded">{{ contact_bad }}</td>
                        {% endif %}
                    {% else %}
                        <td class="padded"><a href="{% url 'farm_invite:invite_listing' %}">Request Slot</a></td>
                    {% endif %}

                </tr>

                {% endfor %}
            {% endif %}

        </table>

    </div>
</div>



{% endblock %}

imrunicorn/farminvite/templates/farminvite/chart_menu.html
<h3><i>Farm Invite Menu</i></h3> <br />
<a class="dropdown-item" href="{% url 'farm_invite:home' %}"> Home</a> |
<a class="dropdown-item" href="{% url 'farm_invite:how_do_i_sign_up' %}"> Sign Up Info</a> |
<a class="dropdown-item" href="{% url 'farm_invite:invite_listing' %}"> Request Slot</a> |
<a class="dropdown-item" href="{% url 'farm_invite:check_list' %}"> Checklist</a> |
<a class="dropdown-item" href="{% url 'farm_invite:cash_app' %}"> Ca$h App</a> |
<a class="dropdown-item" href="{% url 'farm_invite:missing_contact_info' %}"> Missing Info List</a> |
<a class="dropdown-item" href="{% url 'farm_invite:map_secret_sort_of' %}"> Map</a>

imrunicorn/farminvite/templates/farminvite/coming_soon.html
{% extends "imrunicorn/layout.html" %}

{% block content %}

<div class="jumbotron wallpapered">

    <h1 style="text-shadow: 4px 3px 5px #CE5937;
                      font-family: 'Comic Sans MS', cursive, sans-serif;
                      font-size: 73px;
                      font-weight: 400;">Coming Soon</h1>

    <p class="lead">The robot that lives in this website is working hard to bring you this page, eventually.
    </p>
</div>

<div class="row ben_format_pretty">
    <div align="center">
    <div>
        {% include 'farminvite/chart_menu.html' %}
    </div>
</div>
</div>

<br />
<div class="row ben_format_pretty">
    <div class="col-md-12" align="center">
        This page doesn't exist, yet.
    </div>
</div>

<br/><br/>

{% endblock %}

imrunicorn/farminvite/templates/farminvite/donate_cash_app.html
{% extends "imrunicorn/layout.html" %}
{% load static %}
{% block content %}
{% load humanize %}

<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>

<br/>


<div class="row ben_format_pretty">
    <div align="center">
    <div>
        {% include 'farminvite/chart_menu.html' %}
    </div>
</div>
</div>

<br />

<div class="row ben_format_pretty">
    <div align="left" class="col-md-12">
        <div align="center" class="col-md-12">
            <p>Want to help out? Feel free to donate. Donations go toward reloading costs, targets and other misc things for the 'range'.
            </p>
            <p>
                <a href="https://cash.app/$BenSpelledABC" target="_blank">
                    <img height="300" src="{% static '/content/cashapp_benspelledabc.jpg' %}"/>
                </a>
            </p>
        </div>
    </div>
</div>

<br/><br/>

{% endblock %}

imrunicorn/farminvite/templates/farminvite/fake_map.html
{% extends "imrunicorn/layout.html" %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <h4>The map isn't public.</h4>
    </div>
</div>

<div class="row ben_format_pretty">
    <div align="center">
    <div>
        {% include 'farminvite/chart_menu.html' %}
    </div>
</div>
</div>

<br />

<div class="row ben_format_pretty">
    <div class="col-md-12" align="center">
        The real map location will get shared w/ you a couple days before your event.
    </div>
</div>

<br/><br/>

{% endblock %}

imrunicorn/farminvite/templates/farminvite/farm_map.html
{% extends "imrunicorn/layout.html" %}

{% block content %}

    {% load static %}
{% load humanize %}
<h2>{{ title }}</h2>
<div class="row ben_format_pretty">
    <div class="col-md-12">
        <h4>This is a very crude map to get to the range at the farm. The road is a
            tractor road therefore low riding cars will not make it! When GPS
            says you are there and you start to go in the driveway
            STAY LEFT (<span style="color: red; background-color: #0f0f0f ">RED</span>).
            <br /><br />If you go to the
            right (<span style="color: blue; background-color: #0f0f0f ">BLUE</span>) you will end up at
            the wrong section of the property.
            <br /><br />The (<span style="color: white; background-color: #0f0f0f ">White</span>)
            circle on the map is where a Backhoe/tractor MIGHT be parked. This is
            also the most likely spot your car will bottom out if it's too low. Watch the road!
            <br /><br />It might even be worth telling me the color/type of car you're driving BEFORE
            you come onto the property. There are no trespassing signs up, don't get caught with
            your pants down.!

        </h4>
    </div>
</div>
<hr/>


<div class="row ben_format_pretty">
    <div align="center">
    <div>
        {% include 'farminvite/chart_menu.html' %}
    </div>
</div>
</div>

<br />
<div class="row">
    <div class="col-md-12" align="center">
        1700 Indian Valley Trail Westminster, MD 21158<br />
        <img src="{% static '/content/farmMap.png' %}" />
    </div>
</div>

<br/><br/>

{% endblock %}

imrunicorn/farminvite/templates/farminvite/invite_listing_form.html
{% extends "imrunicorn/layout.html" %}
{% load crispy_forms_tags %}

{% block content %}

{% load static %}
{% load humanize %}


<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{{ blurb }}</p>
</div>

<div class="row ben_format_pretty">
    <div align="center">
    <div>
        {% include 'farminvite/chart_menu.html' %}
    </div>
</div>
</div>

<br />

<div class="row ben_format_pretty">
    <div class="col-md-4" align="center">
        <h3>All invites are "all day" now instead of 4hour timeslots!</h3><br /><br />
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Submit</button>
        </form>
    </div>
</div>

<br/><br/>

{% endblock %}

imrunicorn/farminvite/templates/farminvite/missing_contact_info.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}

{% block content %}
{% load humanize %}

<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">Contact info <strong>MUST</strong> be 100% now.</p>
</div>


<div class="row ben_format_pretty">
    <div align="center">
    <div>
        {% include 'farminvite/chart_menu.html' %}
    </div>
</div>
</div>

<br />

<div class="row ben_format_pretty">
    <div class="col-md-12">
        {% autoescape off %}
        <h4>{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</h4>
        {% endautoescape %}
    </div>
</div>
<br /><br />

<table width="65%" border="1" align="center">
    <tr bgcolor="#808080">
        <th bgcolor="808080" style="text-align: center">
            Invite Date
        </th>
        </th>
        <th bgcolor="808080" style="text-align: center">
            Display Name
        </th>
        <th bgcolor="808080" style="text-align: center">
            Phone On File
        </th>
        <th bgcolor="808080" style="text-align: center">
            EMail On File
        </th>

    </tr>

    {% if all_invites != None %}
    {% for invite in all_invites %}

    {% if invite.Invite_Display_Name != 'SLOT AVAILABLE' %}
    <tr bgcolor="#F5F5F5">
        <td id="td-ocw">{{ invite.Invite_Date|date:'m/d/Y' }} </td>

         {% if request.user|has_group:"farminvite_editor" %}
                <td data-toggle="tooltip"
                    title="RealName: {{ invite.Real_Name }}  --  Phone: {{ invite.Phone_Number }}  --  E-Mail: {{ invite.EMail }}">
                    <a href="/admin/farminvite/invitelisting/{{ invite.pk }}/change/" target="_blank"><i class="fas fa-edit"></i></a>
                    {{ invite.Invite_Display_Name }}
                </td>
                {% else %}
                <td data-toggle="tooltip" title="Info Redacted">{{ invite.Invite_Display_Name }}</td>
                {% endif %}

        <td id="td-ocw">{% if invite.Phone_Number %}True{% else %}<strong>False</strong>{% endif %}</td>
        <td id="td-ocw">{% if invite.EMail %}True{% else %}<strong>False</strong>{% endif %}</td>
    </tr>

    {% endif %}

    {% endfor %}
    {% endif %}

</table>


<br/><br/>


{% endblock %}